### ISSUE TITLE
No need to wait after Wire.requestFrom() and Wire.endTransmission should not be used after a Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [Ircam-R-IoT/bitalino-riot-firmware#1]
In the file "LSM9DS1.cpp", you can remove all the `while (Wire.available() < 1);` and `Wire.endTransmission();` after a Wire.requestFrom().
Explanation: [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes), number 1 and 2.

**Comment by flety-emmanuel** [comment]
fixed thanks a lot
